name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      
      - name: Install dependencies
        run: npm install
      
      - name: Lint
        env:
          SKIP_ENV_VALIDATIONS: "true"
        run: npm run lint
      
      - name: Start docker containers
        env:
          POSTGRES_DB: "test_custom_auth"
          POSTGRES_USER: "username"
          POSTGRES_PASSWORD: "password"
        run: |
          docker compose up -d
          # Wait for services to be ready (maybe add health checks)
          sleep 10
          docker ps

      - name: Build
        env:
          NODE_ENV: "production"
          SKIP_ENV_VALIDATIONS: "true"
        run: npm run build
